# Generated by Django 4.0.3 on 2022-04-04 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 22, 9, 43, 62453), verbose_name='date inserted'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 22, 9, 43, 62453), verbose_name='date inserted'),
        ),
    ]
